name: audit
on:
  pull_request:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-audit
  cancel-in-progress: true
jobs:
  clamav:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          fetch-depth: '0'
      - uses: djdefi/gitavscan@1d3a74e51f4e9f51a06767a7175ad5e5ff295130 # 22
        with:
          full: '--full'
  trivy:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions:
      contents: read
      issues: write
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - uses: aquasecurity/trivy-action@76071ef0d7ec797419534a183b498b4d6366cf37 # 0.31.0
        with:
          github-pat: ${{ secrets.GITHUB_TOKEN }}
          scan-type: fs
          format: json
          output: result.json
          ignore-unfixed: true
      - uses: CemitDigital/trivy-report-issue-action@1d2075ae05e2c6fe081f1f781aed6fc3a731e157 # v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          input-filename: result.json
