name: github-actions-cache
on:
  push:
    branches:
      - main
  workflow_dispatch:
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-github-actions-cache
  cancel-in-progress: true
jobs:
  clean:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    permissions:
      actions: write
      contents: read
      pull-requests: read
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - uses: mokmok-dev/delete-actions-cache@1fa5128bc165eab45fecaf3e949e211f0db5a7a9 # v0.1.2
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
