name: toml
on:
  pull_request:
    paths:
      - '**/*.toml'
  workflow_dispatch:
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-toml
  cancel-in-progress: true
jobs:
  taplo:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - uses: actions-rust-lang/setup-rust-toolchain@fb51252c7ba57d633bc668f941da052e410add48 # v1.13.0
      - uses: taiki-e/install-action@9ba3ac3fd006a70c6e186a683577abc1ccf0ff3a # v2.54.0
        with:
          tool: taplo
      - run: taplo format --check --colors never
